# This is a basic workflow to help you get started with Actions

name: deploy-blogs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
#    paths:
#      - packages/blogs/**.*
#      - .github/workflows/blogs-deploy.yml

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Runs a single command using the runners shell
    - name: Install NPM packages
      run: yarn
    - name: Build artifact
      run: yarn workspace blogs build

    - name: Vercel Action
      uses: amondnet/vercel-action@v19
      with:
        vercel-token: ${{ secrets.ZEIT_TOKEN }} # Required
        vercel-org-id: ${{ secrets.ZEIT_ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.ZEIT_PROJECT_ID}} #Required
        working-directory: ./
        vercel-args: '--prod'
